ui-onboarding:
  welcomeNoticeVersion: 2026-08-13.1
mnemon:
  displayMode: buildin
  cliPath: @@MNEMON_CLI@@
dsh-desktop:
  mode: compatibility
ui-theme:
  preference: system
mnemon-ui:
  turnBar: false
